### PR TITLE
fix: added useNativeDriver:true to Animated config to prevent warning

### PR DESCRIPTION
**Pull request by ThaJay**
solves: https://github.com/sidevesh/react-native-fab/issues/35

### CODE REVIEW

**Comment by mateutek** [comment]
Please merge this PR

**Comment by ThaJay** [comment]
@sidevesh

**Comment by WeslleyNasRocha** [comment]
bump?

**Comment by ThaJay** [comment]
The repo is still active ...
https://github.com/sidevesh/react-native-fab/commits/master

@sidevesh Is there a reason behind the 8 month silence?

**Comment by WeslleyNasRocha** [comment]
I've made a fork of this repo, migrated it to typescript and fixed this issue, you can install it from here

https://github.com/WeslleyNasRocha/rn-fab
https://www.npmjs.com/package/rn-fab-animated

**Pull request merged**
